/*
 * Generated by gloam 0.5.1.
 *
 *   gloam --api gl:core=3.3,gles2=3.0 --merge --extensions GL_KHR_debug,GL_EXT_texture_filter_anisotropic --out-path gl-triangle/gloam c --alias
 *
 * Extensions: 2 explicit (2 included)
 *
 * Copyright (c) 2026 Steven Noonan
 * SPDX-License-Identifier: MIT
 *
 * Portions derived from Khronos Group XML API Registry specifications.
 * Copyright (c) 2013-2026 The Khronos Group Inc.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Portions derived from xxHash.
 * Copyright (c) 2012-2026 Yann Collet.
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Includes extensions from the ANGLE project.
 * Copyright (c) 2018-2026 The ANGLE Project Authors.
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Generated from the following upstream sources:
 *
 *   angle/angle (6e09ee6)
 *     scripts/gl_angle_ext.xml (blob 1c4b34c)
 *   Cyan4973/xxHash (e573d4d)
 *     xxhash.h (blob dceb921)
 *   KhronosGroup/EGL-Registry (3d7796b)
 *     api/KHR/khrplatform.h (blob 0164644)
 *   KhronosGroup/OpenGL-Registry (9d527db)
 *     xml/gl.xml (blob 902d7aa)
 *   tycho/gloam-registry (1f5959b)
 *     xml/glsl_exts.xml (blob 943fe5f)
 *
 * DO NOT EDIT. This file is generated by gloam and will be overwritten;
 * make changes to the gloam invocation or inputs, not to this file.
 */

#include <gloam/gl.h>


#include <stdlib.h>  /* calloc, free    */
#include <stddef.h>
#include <stdio.h>   /* sscanf          */
#include <string.h>  /* strlen, strncmp */

#if defined(__x86_64__) || defined(__i386__) || defined(_M_IX86) || defined(_M_X64)
#  ifndef XXH_VECTOR
#    define XXH_VECTOR XXH_SSE2
#  endif
#  include <immintrin.h>
#elif defined(__aarch64__) || defined(__arm__) || defined(_M_ARM) || defined(_M_ARM64)
#  ifndef XXH_VECTOR
#    define XXH_VECTOR XXH_NEON
#  endif
#  include <arm_neon.h>
#endif
#ifndef GLOAM_EXTERNAL_XXHASH
#  define XXH_INLINE_ALL
#  define XXH_NO_STREAM
#endif
#include "xxhash.h"

#ifndef GLOAM_IMPL_UTIL_C_
#define GLOAM_IMPL_UTIL_C_

/* MSVC vs GCC/Clang sscanf */
#ifdef _MSC_VER
#  define GLOAM_IMPL_UTIL_SSCANF sscanf_s
#else
#  define GLOAM_IMPL_UTIL_SSCANF sscanf
#endif

/* GLOAM_NO_INLINE — suppress inlining on functions that should stay out of
 * the hot path (sort, hash, etc.) to avoid code bloat at call sites.
 */
#ifdef _MSC_VER
#  define GLOAM_NO_INLINE __declspec(noinline)
#else
#  define GLOAM_NO_INLINE __attribute__((noinline))
#endif

#define GLOAM_ARRAYSIZE(x) (sizeof(x) / sizeof((x)[0]))
#define GLOAM_UNUSED(x)    ((void)(x))

/* Contiguous run of pfnArray slots belonging to one feature or extension.
 * Used by the range-based PFN loading loop.
 */
typedef struct {
    uint16_t extension; /* index into featArray or extArray  */
    uint16_t start;     /* first pfnArray index in this run  */
    uint16_t count;     /* number of consecutive slots       */
} GloamPfnRange_t;

/* Bijective alias pair: if canonical slot is null but secondary is loaded
 * (or vice versa), the loaded pointer is propagated to both slots.
 */
typedef struct {
    uint16_t first;  /* canonical (shortest name) pfnArray index */
    uint16_t second; /* alias pfnArray index                     */
} GloamAliasPair_t;

#endif /* GLOAM_IMPL_UTIL_C_ */


#ifndef GLOAM_IMPL_HASHSEARCH_C_
#define GLOAM_IMPL_HASHSEARCH_C_

/* gloam_sort_hashes — in-place Shellsort on a uint64_t array.
 *
 * Ciura (2001) gap sequence.  Gaps larger than n are skipped at runtime so
 * small arrays (< 10 extensions) take only a couple of passes.  No heap
 * allocation; code size is ~80 bytes on x86-64.
 */
GLOAM_NO_INLINE static void gloam_sort_hashes(uint64_t *a, size_t n)
{
    static const size_t kGaps[] = { 701, 301, 132, 57, 23, 10, 4, 1 };
    size_t gi = 0;
    if (!a || n < 2) return;
    /* Skip gaps that are larger than the array. */
    while (gi < GLOAM_ARRAYSIZE(kGaps) && kGaps[gi] >= n) ++gi;
    for (; gi < GLOAM_ARRAYSIZE(kGaps); ++gi) {
        size_t gap = kGaps[gi], i;
        for (i = gap; i < n; ++i) {
            uint64_t v = a[i];
            size_t j = i;
            while (j >= gap && a[j - gap] > v) {
                a[j] = a[j - gap];
                j -= gap;
            }
            a[j] = v;
        }
    }
}

/* gloam_hash_search — binary search for `target` in a sorted uint64_t array.
 * Returns 1 if found, 0 otherwise.
 */
GLOAM_NO_INLINE static int gloam_hash_search(const uint64_t *arr, uint32_t size, uint64_t target)
{
    int32_t lo = 0, hi = (int32_t)size - 1;
    while (lo <= hi) {
        int32_t mid = lo + (hi - lo) / 2;
        if (arr[mid] == target) return 1;
        if (arr[mid] < target)  lo = mid + 1;
        else                    hi = mid - 1;
    }
    return 0;
}

/* gloam_hash_string — hash a NUL-terminated string with XXH3-64.
 * The same algorithm is used at generator time to pre-bake kExtHashes[],
 * guaranteeing that driver-reported names and the embedded table match.
 */
GLOAM_NO_INLINE static uint64_t gloam_hash_string(const char *str, size_t length)
{
    return XXH3_64bits(str, length);
}

/* ---- Extension string tokenizer ------------------------------------------
   Two-pass tokenize-and-hash for space-separated extension strings (GL, EGL,
   GLX, WGL).  First pass counts tokens, second pass hashes them.  Result is
   sorted for binary search in find_extensions. */
GLOAM_NO_INLINE static int gloam_hash_ext_string(const char *ext_str, uint64_t **out_exts, uint32_t *out_num_exts)
{
    const char *cur, *next;
    uint64_t *exts = NULL;
    uint32_t num_exts = 0, j;

    for (j = 0; j < 2; ++j) {
        num_exts = 0;
        cur  = ext_str;
        next = cur + strcspn(cur, " ");
        while (1) {
            size_t len;
            cur += strspn(cur, " ");
            if (!cur[0])
                break;
            len = (size_t)(next - cur);
            if (exts)
                exts[num_exts] = gloam_hash_string(cur, len);
            ++num_exts;
            cur  = next + strspn(next, " ");
            next = cur  + strcspn(cur,  " ");
        }
        if (!exts) {
            exts = (uint64_t *)calloc(num_exts, sizeof(uint64_t));
            if (!exts)
                return 0;
        }
    }

    gloam_sort_hashes(exts, num_exts);
    *out_exts     = exts;
    *out_num_exts = num_exts;
    return 1;
}
#endif /* GLOAM_IMPL_HASHSEARCH_C_ */


/* ---- Global context (zero-initialised at program startup) ---------------- */
#ifdef __cplusplus
GloamGLContext gloam_gl_context = {};
#else
GloamGLContext gloam_gl_context = { 0 };
#endif

/* ---- Function name table -------------------------------------------------
 * Command names stored as a single NUL-terminated string blob with a parallel
 * offset table for O(1) indexing. This avoids one pointer (8 bytes on 64-bit)
 * plus one relocation entry (~24 bytes in PIC builds) per command compared to
 * the traditional const char * const [] approach.
 */
static const uint32_t kFnCount_GL = 385;

static const char kFnNameData_GL[] =
    /*     0 */ "glClearDepth\0"
    /*    13 */ "glDepthRange\0"
    /*    26 */ "glDrawBuffer\0"
    /*    39 */ "glGetDoublev\0"
    /*    52 */ "glGetTexImage\0"
    /*    66 */ "glGetTexLevelParameterfv\0"
    /*    91 */ "glGetTexLevelParameteriv\0"
    /*   116 */ "glLogicOp\0"
    /*   126 */ "glPixelStoref\0"
    /*   140 */ "glPointSize\0"
    /*   152 */ "glPolygonMode\0"
    /*   166 */ "glTexImage1D\0"
    /*   179 */ "glBlendFunc\0"
    /*   191 */ "glClear\0"
    /*   199 */ "glClearColor\0"
    /*   212 */ "glClearStencil\0"
    /*   227 */ "glColorMask\0"
    /*   239 */ "glCullFace\0"
    /*   250 */ "glDepthFunc\0"
    /*   262 */ "glDepthMask\0"
    /*   274 */ "glDisable\0"
    /*   284 */ "glEnable\0"
    /*   293 */ "glFinish\0"
    /*   302 */ "glFlush\0"
    /*   310 */ "glFrontFace\0"
    /*   322 */ "glGetBooleanv\0"
    /*   336 */ "glGetError\0"
    /*   347 */ "glGetFloatv\0"
    /*   359 */ "glGetIntegerv\0"
    /*   373 */ "glGetString\0"
    /*   385 */ "glGetTexParameterfv\0"
    /*   405 */ "glGetTexParameteriv\0"
    /*   425 */ "glHint\0"
    /*   432 */ "glIsEnabled\0"
    /*   444 */ "glLineWidth\0"
    /*   456 */ "glPixelStorei\0"
    /*   470 */ "glReadPixels\0"
    /*   483 */ "glScissor\0"
    /*   493 */ "glStencilFunc\0"
    /*   507 */ "glStencilMask\0"
    /*   521 */ "glStencilOp\0"
    /*   533 */ "glTexImage2D\0"
    /*   546 */ "glTexParameterf\0"
    /*   562 */ "glTexParameterfv\0"
    /*   579 */ "glTexParameteri\0"
    /*   595 */ "glTexParameteriv\0"
    /*   612 */ "glViewport\0"
    /*   623 */ "glReadBuffer\0"
    /*   636 */ "glCopyTexImage1D\0"
    /*   653 */ "glCopyTexSubImage1D\0"
    /*   673 */ "glTexSubImage1D\0"
    /*   689 */ "glBindTexture\0"
    /*   703 */ "glCopyTexImage2D\0"
    /*   720 */ "glCopyTexSubImage2D\0"
    /*   740 */ "glDeleteTextures\0"
    /*   757 */ "glDrawArrays\0"
    /*   770 */ "glDrawElements\0"
    /*   785 */ "glGenTextures\0"
    /*   799 */ "glIsTexture\0"
    /*   811 */ "glPolygonOffset\0"
    /*   827 */ "glTexSubImage2D\0"
    /*   843 */ "glCopyTexSubImage3D\0"
    /*   863 */ "glDrawRangeElements\0"
    /*   883 */ "glTexImage3D\0"
    /*   896 */ "glTexSubImage3D\0"
    /*   912 */ "glCompressedTexImage1D\0"
    /*   935 */ "glCompressedTexSubImage1D\0"
    /*   961 */ "glGetCompressedTexImage\0"
    /*   985 */ "glActiveTexture\0"
    /*  1001 */ "glCompressedTexImage2D\0"
    /*  1024 */ "glCompressedTexSubImage2D\0"
    /*  1050 */ "glSampleCoverage\0"
    /*  1067 */ "glCompressedTexImage3D\0"
    /*  1090 */ "glCompressedTexSubImage3D\0"
    /*  1116 */ "glMultiDrawArrays\0"
    /*  1134 */ "glMultiDrawElements\0"
    /*  1154 */ "glPointParameterf\0"
    /*  1172 */ "glPointParameterfv\0"
    /*  1191 */ "glPointParameteri\0"
    /*  1209 */ "glPointParameteriv\0"
    /*  1228 */ "glBlendColor\0"
    /*  1241 */ "glBlendEquation\0"
    /*  1257 */ "glBlendFuncSeparate\0"
    /*  1277 */ "glGetBufferSubData\0"
    /*  1296 */ "glGetQueryObjectiv\0"
    /*  1315 */ "glMapBuffer\0"
    /*  1327 */ "glBindBuffer\0"
    /*  1340 */ "glBufferData\0"
    /*  1353 */ "glBufferSubData\0"
    /*  1369 */ "glDeleteBuffers\0"
    /*  1385 */ "glGenBuffers\0"
    /*  1398 */ "glGetBufferParameteriv\0"
    /*  1421 */ "glIsBuffer\0"
    /*  1432 */ "glBeginQuery\0"
    /*  1445 */ "glDeleteQueries\0"
    /*  1461 */ "glEndQuery\0"
    /*  1472 */ "glGenQueries\0"
    /*  1485 */ "glGetBufferPointerv\0"
    /*  1505 */ "glGetQueryObjectuiv\0"
    /*  1525 */ "glGetQueryiv\0"
    /*  1538 */ "glIsQuery\0"
    /*  1548 */ "glUnmapBuffer\0"
    /*  1562 */ "glGetVertexAttribdv\0"
    /*  1582 */ "glVertexAttrib1d\0"
    /*  1599 */ "glVertexAttrib1dv\0"
    /*  1617 */ "glVertexAttrib1s\0"
    /*  1634 */ "glVertexAttrib1sv\0"
    /*  1652 */ "glVertexAttrib2d\0"
    /*  1669 */ "glVertexAttrib2dv\0"
    /*  1687 */ "glVertexAttrib2s\0"
    /*  1704 */ "glVertexAttrib2sv\0"
    /*  1722 */ "glVertexAttrib3d\0"
    /*  1739 */ "glVertexAttrib3dv\0"
    /*  1757 */ "glVertexAttrib3s\0"
    /*  1774 */ "glVertexAttrib3sv\0"
    /*  1792 */ "glVertexAttrib4Nbv\0"
    /*  1811 */ "glVertexAttrib4Niv\0"
    /*  1830 */ "glVertexAttrib4Nsv\0"
    /*  1849 */ "glVertexAttrib4Nub\0"
    /*  1868 */ "glVertexAttrib4Nubv\0"
    /*  1888 */ "glVertexAttrib4Nuiv\0"
    /*  1908 */ "glVertexAttrib4Nusv\0"
    /*  1928 */ "glVertexAttrib4bv\0"
    /*  1946 */ "glVertexAttrib4d\0"
    /*  1963 */ "glVertexAttrib4dv\0"
    /*  1981 */ "glVertexAttrib4iv\0"
    /*  1999 */ "glVertexAttrib4s\0"
    /*  2016 */ "glVertexAttrib4sv\0"
    /*  2034 */ "glVertexAttrib4ubv\0"
    /*  2053 */ "glVertexAttrib4uiv\0"
    /*  2072 */ "glVertexAttrib4usv\0"
    /*  2091 */ "glAttachShader\0"
    /*  2106 */ "glBindAttribLocation\0"
    /*  2127 */ "glBlendEquationSeparate\0"
    /*  2151 */ "glCompileShader\0"
    /*  2167 */ "glCreateProgram\0"
    /*  2183 */ "glCreateShader\0"
    /*  2198 */ "glDeleteProgram\0"
    /*  2214 */ "glDeleteShader\0"
    /*  2229 */ "glDetachShader\0"
    /*  2244 */ "glDisableVertexAttribArray\0"
    /*  2271 */ "glEnableVertexAttribArray\0"
    /*  2297 */ "glGetActiveAttrib\0"
    /*  2315 */ "glGetActiveUniform\0"
    /*  2334 */ "glGetAttachedShaders\0"
    /*  2355 */ "glGetAttribLocation\0"
    /*  2375 */ "glGetProgramInfoLog\0"
    /*  2395 */ "glGetProgramiv\0"
    /*  2410 */ "glGetShaderInfoLog\0"
    /*  2429 */ "glGetShaderSource\0"
    /*  2447 */ "glGetShaderiv\0"
    /*  2461 */ "glGetUniformLocation\0"
    /*  2482 */ "glGetUniformfv\0"
    /*  2497 */ "glGetUniformiv\0"
    /*  2512 */ "glGetVertexAttribPointerv\0"
    /*  2538 */ "glGetVertexAttribfv\0"
    /*  2558 */ "glGetVertexAttribiv\0"
    /*  2578 */ "glIsProgram\0"
    /*  2590 */ "glIsShader\0"
    /*  2601 */ "glLinkProgram\0"
    /*  2615 */ "glShaderSource\0"
    /*  2630 */ "glStencilFuncSeparate\0"
    /*  2652 */ "glStencilMaskSeparate\0"
    /*  2674 */ "glStencilOpSeparate\0"
    /*  2694 */ "glUniform1f\0"
    /*  2706 */ "glUniform1fv\0"
    /*  2719 */ "glUniform1i\0"
    /*  2731 */ "glUniform1iv\0"
    /*  2744 */ "glUniform2f\0"
    /*  2756 */ "glUniform2fv\0"
    /*  2769 */ "glUniform2i\0"
    /*  2781 */ "glUniform2iv\0"
    /*  2794 */ "glUniform3f\0"
    /*  2806 */ "glUniform3fv\0"
    /*  2819 */ "glUniform3i\0"
    /*  2831 */ "glUniform3iv\0"
    /*  2844 */ "glUniform4f\0"
    /*  2856 */ "glUniform4fv\0"
    /*  2869 */ "glUniform4i\0"
    /*  2881 */ "glUniform4iv\0"
    /*  2894 */ "glUniformMatrix2fv\0"
    /*  2913 */ "glUniformMatrix3fv\0"
    /*  2932 */ "glUniformMatrix4fv\0"
    /*  2951 */ "glUseProgram\0"
    /*  2964 */ "glValidateProgram\0"
    /*  2982 */ "glVertexAttrib1f\0"
    /*  2999 */ "glVertexAttrib1fv\0"
    /*  3017 */ "glVertexAttrib2f\0"
    /*  3034 */ "glVertexAttrib2fv\0"
    /*  3052 */ "glVertexAttrib3f\0"
    /*  3069 */ "glVertexAttrib3fv\0"
    /*  3087 */ "glVertexAttrib4f\0"
    /*  3104 */ "glVertexAttrib4fv\0"
    /*  3122 */ "glVertexAttribPointer\0"
    /*  3144 */ "glDrawBuffers\0"
    /*  3158 */ "glUniformMatrix2x3fv\0"
    /*  3179 */ "glUniformMatrix2x4fv\0"
    /*  3200 */ "glUniformMatrix3x2fv\0"
    /*  3221 */ "glUniformMatrix3x4fv\0"
    /*  3242 */ "glUniformMatrix4x2fv\0"
    /*  3263 */ "glUniformMatrix4x3fv\0"
    /*  3284 */ "glBeginConditionalRender\0"
    /*  3309 */ "glBindFragDataLocation\0"
    /*  3332 */ "glClampColor\0"
    /*  3345 */ "glColorMaski\0"
    /*  3358 */ "glDisablei\0"
    /*  3369 */ "glEnablei\0"
    /*  3379 */ "glEndConditionalRender\0"
    /*  3402 */ "glFramebufferTexture1D\0"
    /*  3425 */ "glFramebufferTexture3D\0"
    /*  3448 */ "glGetBooleani_v\0"
    /*  3464 */ "glGetTexParameterIiv\0"
    /*  3485 */ "glGetTexParameterIuiv\0"
    /*  3507 */ "glIsEnabledi\0"
    /*  3520 */ "glTexParameterIiv\0"
    /*  3538 */ "glTexParameterIuiv\0"
    /*  3557 */ "glVertexAttribI1i\0"
    /*  3575 */ "glVertexAttribI1iv\0"
    /*  3594 */ "glVertexAttribI1ui\0"
    /*  3613 */ "glVertexAttribI1uiv\0"
    /*  3633 */ "glVertexAttribI2i\0"
    /*  3651 */ "glVertexAttribI2iv\0"
    /*  3670 */ "glVertexAttribI2ui\0"
    /*  3689 */ "glVertexAttribI2uiv\0"
    /*  3709 */ "glVertexAttribI3i\0"
    /*  3727 */ "glVertexAttribI3iv\0"
    /*  3746 */ "glVertexAttribI3ui\0"
    /*  3765 */ "glVertexAttribI3uiv\0"
    /*  3785 */ "glVertexAttribI4bv\0"
    /*  3804 */ "glVertexAttribI4sv\0"
    /*  3823 */ "glVertexAttribI4ubv\0"
    /*  3843 */ "glVertexAttribI4usv\0"
    /*  3863 */ "glBindBufferBase\0"
    /*  3880 */ "glBindBufferRange\0"
    /*  3898 */ "glGetIntegeri_v\0"
    /*  3914 */ "glBindFramebuffer\0"
    /*  3932 */ "glBindRenderbuffer\0"
    /*  3951 */ "glCheckFramebufferStatus\0"
    /*  3976 */ "glDeleteFramebuffers\0"
    /*  3997 */ "glDeleteRenderbuffers\0"
    /*  4019 */ "glFramebufferRenderbuffer\0"
    /*  4045 */ "glFramebufferTexture2D\0"
    /*  4068 */ "glGenFramebuffers\0"
    /*  4086 */ "glGenRenderbuffers\0"
    /*  4105 */ "glGenerateMipmap\0"
    /*  4122 */ "glGetFramebufferAttachmentParameteriv\0"
    /*  4160 */ "glGetRenderbufferParameteriv\0"
    /*  4189 */ "glIsFramebuffer\0"
    /*  4205 */ "glIsRenderbuffer\0"
    /*  4222 */ "glRenderbufferStorage\0"
    /*  4244 */ "glBeginTransformFeedback\0"
    /*  4269 */ "glBindVertexArray\0"
    /*  4287 */ "glBlitFramebuffer\0"
    /*  4305 */ "glClearBufferfi\0"
    /*  4321 */ "glClearBufferfv\0"
    /*  4337 */ "glClearBufferiv\0"
    /*  4353 */ "glClearBufferuiv\0"
    /*  4370 */ "glDeleteVertexArrays\0"
    /*  4391 */ "glEndTransformFeedback\0"
    /*  4414 */ "glFlushMappedBufferRange\0"
    /*  4439 */ "glFramebufferTextureLayer\0"
    /*  4465 */ "glGenVertexArrays\0"
    /*  4483 */ "glGetFragDataLocation\0"
    /*  4505 */ "glGetStringi\0"
    /*  4518 */ "glGetTransformFeedbackVarying\0"
    /*  4548 */ "glGetUniformuiv\0"
    /*  4564 */ "glGetVertexAttribIiv\0"
    /*  4585 */ "glGetVertexAttribIuiv\0"
    /*  4607 */ "glIsVertexArray\0"
    /*  4623 */ "glMapBufferRange\0"
    /*  4640 */ "glRenderbufferStorageMultisample\0"
    /*  4673 */ "glTransformFeedbackVaryings\0"
    /*  4701 */ "glUniform1ui\0"
    /*  4714 */ "glUniform1uiv\0"
    /*  4728 */ "glUniform2ui\0"
    /*  4741 */ "glUniform2uiv\0"
    /*  4755 */ "glUniform3ui\0"
    /*  4768 */ "glUniform3uiv\0"
    /*  4782 */ "glUniform4ui\0"
    /*  4795 */ "glUniform4uiv\0"
    /*  4809 */ "glVertexAttribI4i\0"
    /*  4827 */ "glVertexAttribI4iv\0"
    /*  4846 */ "glVertexAttribI4ui\0"
    /*  4865 */ "glVertexAttribI4uiv\0"
    /*  4885 */ "glVertexAttribIPointer\0"
    /*  4908 */ "glGetActiveUniformName\0"
    /*  4931 */ "glPrimitiveRestartIndex\0"
    /*  4955 */ "glTexBuffer\0"
    /*  4967 */ "glCopyBufferSubData\0"
    /*  4987 */ "glDrawArraysInstanced\0"
    /*  5009 */ "glDrawElementsInstanced\0"
    /*  5033 */ "glGetActiveUniformBlockName\0"
    /*  5061 */ "glGetActiveUniformBlockiv\0"
    /*  5087 */ "glGetActiveUniformsiv\0"
    /*  5109 */ "glGetUniformBlockIndex\0"
    /*  5132 */ "glGetUniformIndices\0"
    /*  5152 */ "glUniformBlockBinding\0"
    /*  5174 */ "glDrawElementsBaseVertex\0"
    /*  5199 */ "glDrawElementsInstancedBaseVertex\0"
    /*  5233 */ "glDrawRangeElementsBaseVertex\0"
    /*  5263 */ "glFramebufferTexture\0"
    /*  5284 */ "glGetMultisamplefv\0"
    /*  5303 */ "glMultiDrawElementsBaseVertex\0"
    /*  5333 */ "glProvokingVertex\0"
    /*  5351 */ "glSampleMaski\0"
    /*  5365 */ "glTexImage2DMultisample\0"
    /*  5389 */ "glTexImage3DMultisample\0"
    /*  5413 */ "glClientWaitSync\0"
    /*  5430 */ "glDeleteSync\0"
    /*  5443 */ "glFenceSync\0"
    /*  5455 */ "glGetBufferParameteri64v\0"
    /*  5480 */ "glGetInteger64i_v\0"
    /*  5498 */ "glGetInteger64v\0"
    /*  5514 */ "glGetSynciv\0"
    /*  5526 */ "glIsSync\0"
    /*  5535 */ "glWaitSync\0"
    /*  5546 */ "glBindFragDataLocationIndexed\0"
    /*  5576 */ "glGetFragDataIndex\0"
    /*  5595 */ "glGetQueryObjecti64v\0"
    /*  5616 */ "glGetQueryObjectui64v\0"
    /*  5638 */ "glGetSamplerParameterIiv\0"
    /*  5663 */ "glGetSamplerParameterIuiv\0"
    /*  5689 */ "glQueryCounter\0"
    /*  5704 */ "glSamplerParameterIiv\0"
    /*  5726 */ "glSamplerParameterIuiv\0"
    /*  5749 */ "glVertexAttribP1ui\0"
    /*  5768 */ "glVertexAttribP1uiv\0"
    /*  5788 */ "glVertexAttribP2ui\0"
    /*  5807 */ "glVertexAttribP2uiv\0"
    /*  5827 */ "glVertexAttribP3ui\0"
    /*  5846 */ "glVertexAttribP3uiv\0"
    /*  5866 */ "glVertexAttribP4ui\0"
    /*  5885 */ "glVertexAttribP4uiv\0"
    /*  5905 */ "glBindSampler\0"
    /*  5919 */ "glDeleteSamplers\0"
    /*  5936 */ "glGenSamplers\0"
    /*  5950 */ "glGetSamplerParameterfv\0"
    /*  5974 */ "glGetSamplerParameteriv\0"
    /*  5998 */ "glIsSampler\0"
    /*  6010 */ "glSamplerParameterf\0"
    /*  6030 */ "glSamplerParameterfv\0"
    /*  6051 */ "glSamplerParameteri\0"
    /*  6071 */ "glSamplerParameteriv\0"
    /*  6092 */ "glVertexAttribDivisor\0"
    /*  6114 */ "glClearDepthf\0"
    /*  6128 */ "glDepthRangef\0"
    /*  6142 */ "glGetShaderPrecisionFormat\0"
    /*  6169 */ "glReleaseShaderCompiler\0"
    /*  6193 */ "glShaderBinary\0"
    /*  6208 */ "glBindTransformFeedback\0"
    /*  6232 */ "glDeleteTransformFeedbacks\0"
    /*  6259 */ "glGenTransformFeedbacks\0"
    /*  6283 */ "glGetInternalformativ\0"
    /*  6305 */ "glGetProgramBinary\0"
    /*  6324 */ "glInvalidateFramebuffer\0"
    /*  6348 */ "glInvalidateSubFramebuffer\0"
    /*  6375 */ "glIsTransformFeedback\0"
    /*  6397 */ "glPauseTransformFeedback\0"
    /*  6422 */ "glProgramBinary\0"
    /*  6438 */ "glProgramParameteri\0"
    /*  6458 */ "glResumeTransformFeedback\0"
    /*  6484 */ "glTexStorage2D\0"
    /*  6499 */ "glTexStorage3D\0"
    /*  6514 */ "glGetPointerv\0"
    /*  6528 */ "glDebugMessageCallback\0"
    /*  6551 */ "glDebugMessageCallbackKHR\0"
    /*  6577 */ "glDebugMessageControl\0"
    /*  6599 */ "glDebugMessageControlKHR\0"
    /*  6624 */ "glDebugMessageInsert\0"
    /*  6645 */ "glDebugMessageInsertKHR\0"
    /*  6669 */ "glGetDebugMessageLog\0"
    /*  6690 */ "glGetDebugMessageLogKHR\0"
    /*  6714 */ "glGetObjectLabel\0"
    /*  6731 */ "glGetObjectLabelKHR\0"
    /*  6751 */ "glGetObjectPtrLabel\0"
    /*  6771 */ "glGetObjectPtrLabelKHR\0"
    /*  6794 */ "glGetPointervKHR\0"
    /*  6811 */ "glObjectLabel\0"
    /*  6825 */ "glObjectLabelKHR\0"
    /*  6842 */ "glObjectPtrLabel\0"
    /*  6859 */ "glObjectPtrLabelKHR\0"
    /*  6879 */ "glPopDebugGroup\0"
    /*  6895 */ "glPopDebugGroupKHR\0"
    /*  6914 */ "glPushDebugGroup\0"
    /*  6931 */ "glPushDebugGroupKHR\0"
;
static const uint16_t kFnNameOffsets_GL[] = {
    /*    0 */     0, /* glClearDepth */
    /*    1 */    13, /* glDepthRange */
    /*    2 */    26, /* glDrawBuffer */
    /*    3 */    39, /* glGetDoublev */
    /*    4 */    52, /* glGetTexImage */
    /*    5 */    66, /* glGetTexLevelParameterfv */
    /*    6 */    91, /* glGetTexLevelParameteriv */
    /*    7 */   116, /* glLogicOp */
    /*    8 */   126, /* glPixelStoref */
    /*    9 */   140, /* glPointSize */
    /*   10 */   152, /* glPolygonMode */
    /*   11 */   166, /* glTexImage1D */
    /*   12 */   179, /* glBlendFunc */
    /*   13 */   191, /* glClear */
    /*   14 */   199, /* glClearColor */
    /*   15 */   212, /* glClearStencil */
    /*   16 */   227, /* glColorMask */
    /*   17 */   239, /* glCullFace */
    /*   18 */   250, /* glDepthFunc */
    /*   19 */   262, /* glDepthMask */
    /*   20 */   274, /* glDisable */
    /*   21 */   284, /* glEnable */
    /*   22 */   293, /* glFinish */
    /*   23 */   302, /* glFlush */
    /*   24 */   310, /* glFrontFace */
    /*   25 */   322, /* glGetBooleanv */
    /*   26 */   336, /* glGetError */
    /*   27 */   347, /* glGetFloatv */
    /*   28 */   359, /* glGetIntegerv */
    /*   29 */   373, /* glGetString */
    /*   30 */   385, /* glGetTexParameterfv */
    /*   31 */   405, /* glGetTexParameteriv */
    /*   32 */   425, /* glHint */
    /*   33 */   432, /* glIsEnabled */
    /*   34 */   444, /* glLineWidth */
    /*   35 */   456, /* glPixelStorei */
    /*   36 */   470, /* glReadPixels */
    /*   37 */   483, /* glScissor */
    /*   38 */   493, /* glStencilFunc */
    /*   39 */   507, /* glStencilMask */
    /*   40 */   521, /* glStencilOp */
    /*   41 */   533, /* glTexImage2D */
    /*   42 */   546, /* glTexParameterf */
    /*   43 */   562, /* glTexParameterfv */
    /*   44 */   579, /* glTexParameteri */
    /*   45 */   595, /* glTexParameteriv */
    /*   46 */   612, /* glViewport */
    /*   47 */   623, /* glReadBuffer */
    /*   48 */   636, /* glCopyTexImage1D */
    /*   49 */   653, /* glCopyTexSubImage1D */
    /*   50 */   673, /* glTexSubImage1D */
    /*   51 */   689, /* glBindTexture */
    /*   52 */   703, /* glCopyTexImage2D */
    /*   53 */   720, /* glCopyTexSubImage2D */
    /*   54 */   740, /* glDeleteTextures */
    /*   55 */   757, /* glDrawArrays */
    /*   56 */   770, /* glDrawElements */
    /*   57 */   785, /* glGenTextures */
    /*   58 */   799, /* glIsTexture */
    /*   59 */   811, /* glPolygonOffset */
    /*   60 */   827, /* glTexSubImage2D */
    /*   61 */   843, /* glCopyTexSubImage3D */
    /*   62 */   863, /* glDrawRangeElements */
    /*   63 */   883, /* glTexImage3D */
    /*   64 */   896, /* glTexSubImage3D */
    /*   65 */   912, /* glCompressedTexImage1D */
    /*   66 */   935, /* glCompressedTexSubImage1D */
    /*   67 */   961, /* glGetCompressedTexImage */
    /*   68 */   985, /* glActiveTexture */
    /*   69 */  1001, /* glCompressedTexImage2D */
    /*   70 */  1024, /* glCompressedTexSubImage2D */
    /*   71 */  1050, /* glSampleCoverage */
    /*   72 */  1067, /* glCompressedTexImage3D */
    /*   73 */  1090, /* glCompressedTexSubImage3D */
    /*   74 */  1116, /* glMultiDrawArrays */
    /*   75 */  1134, /* glMultiDrawElements */
    /*   76 */  1154, /* glPointParameterf */
    /*   77 */  1172, /* glPointParameterfv */
    /*   78 */  1191, /* glPointParameteri */
    /*   79 */  1209, /* glPointParameteriv */
    /*   80 */  1228, /* glBlendColor */
    /*   81 */  1241, /* glBlendEquation */
    /*   82 */  1257, /* glBlendFuncSeparate */
    /*   83 */  1277, /* glGetBufferSubData */
    /*   84 */  1296, /* glGetQueryObjectiv */
    /*   85 */  1315, /* glMapBuffer */
    /*   86 */  1327, /* glBindBuffer */
    /*   87 */  1340, /* glBufferData */
    /*   88 */  1353, /* glBufferSubData */
    /*   89 */  1369, /* glDeleteBuffers */
    /*   90 */  1385, /* glGenBuffers */
    /*   91 */  1398, /* glGetBufferParameteriv */
    /*   92 */  1421, /* glIsBuffer */
    /*   93 */  1432, /* glBeginQuery */
    /*   94 */  1445, /* glDeleteQueries */
    /*   95 */  1461, /* glEndQuery */
    /*   96 */  1472, /* glGenQueries */
    /*   97 */  1485, /* glGetBufferPointerv */
    /*   98 */  1505, /* glGetQueryObjectuiv */
    /*   99 */  1525, /* glGetQueryiv */
    /*  100 */  1538, /* glIsQuery */
    /*  101 */  1548, /* glUnmapBuffer */
    /*  102 */  1562, /* glGetVertexAttribdv */
    /*  103 */  1582, /* glVertexAttrib1d */
    /*  104 */  1599, /* glVertexAttrib1dv */
    /*  105 */  1617, /* glVertexAttrib1s */
    /*  106 */  1634, /* glVertexAttrib1sv */
    /*  107 */  1652, /* glVertexAttrib2d */
    /*  108 */  1669, /* glVertexAttrib2dv */
    /*  109 */  1687, /* glVertexAttrib2s */
    /*  110 */  1704, /* glVertexAttrib2sv */
    /*  111 */  1722, /* glVertexAttrib3d */
    /*  112 */  1739, /* glVertexAttrib3dv */
    /*  113 */  1757, /* glVertexAttrib3s */
    /*  114 */  1774, /* glVertexAttrib3sv */
    /*  115 */  1792, /* glVertexAttrib4Nbv */
    /*  116 */  1811, /* glVertexAttrib4Niv */
    /*  117 */  1830, /* glVertexAttrib4Nsv */
    /*  118 */  1849, /* glVertexAttrib4Nub */
    /*  119 */  1868, /* glVertexAttrib4Nubv */
    /*  120 */  1888, /* glVertexAttrib4Nuiv */
    /*  121 */  1908, /* glVertexAttrib4Nusv */
    /*  122 */  1928, /* glVertexAttrib4bv */
    /*  123 */  1946, /* glVertexAttrib4d */
    /*  124 */  1963, /* glVertexAttrib4dv */
    /*  125 */  1981, /* glVertexAttrib4iv */
    /*  126 */  1999, /* glVertexAttrib4s */
    /*  127 */  2016, /* glVertexAttrib4sv */
    /*  128 */  2034, /* glVertexAttrib4ubv */
    /*  129 */  2053, /* glVertexAttrib4uiv */
    /*  130 */  2072, /* glVertexAttrib4usv */
    /*  131 */  2091, /* glAttachShader */
    /*  132 */  2106, /* glBindAttribLocation */
    /*  133 */  2127, /* glBlendEquationSeparate */
    /*  134 */  2151, /* glCompileShader */
    /*  135 */  2167, /* glCreateProgram */
    /*  136 */  2183, /* glCreateShader */
    /*  137 */  2198, /* glDeleteProgram */
    /*  138 */  2214, /* glDeleteShader */
    /*  139 */  2229, /* glDetachShader */
    /*  140 */  2244, /* glDisableVertexAttribArray */
    /*  141 */  2271, /* glEnableVertexAttribArray */
    /*  142 */  2297, /* glGetActiveAttrib */
    /*  143 */  2315, /* glGetActiveUniform */
    /*  144 */  2334, /* glGetAttachedShaders */
    /*  145 */  2355, /* glGetAttribLocation */
    /*  146 */  2375, /* glGetProgramInfoLog */
    /*  147 */  2395, /* glGetProgramiv */
    /*  148 */  2410, /* glGetShaderInfoLog */
    /*  149 */  2429, /* glGetShaderSource */
    /*  150 */  2447, /* glGetShaderiv */
    /*  151 */  2461, /* glGetUniformLocation */
    /*  152 */  2482, /* glGetUniformfv */
    /*  153 */  2497, /* glGetUniformiv */
    /*  154 */  2512, /* glGetVertexAttribPointerv */
    /*  155 */  2538, /* glGetVertexAttribfv */
    /*  156 */  2558, /* glGetVertexAttribiv */
    /*  157 */  2578, /* glIsProgram */
    /*  158 */  2590, /* glIsShader */
    /*  159 */  2601, /* glLinkProgram */
    /*  160 */  2615, /* glShaderSource */
    /*  161 */  2630, /* glStencilFuncSeparate */
    /*  162 */  2652, /* glStencilMaskSeparate */
    /*  163 */  2674, /* glStencilOpSeparate */
    /*  164 */  2694, /* glUniform1f */
    /*  165 */  2706, /* glUniform1fv */
    /*  166 */  2719, /* glUniform1i */
    /*  167 */  2731, /* glUniform1iv */
    /*  168 */  2744, /* glUniform2f */
    /*  169 */  2756, /* glUniform2fv */
    /*  170 */  2769, /* glUniform2i */
    /*  171 */  2781, /* glUniform2iv */
    /*  172 */  2794, /* glUniform3f */
    /*  173 */  2806, /* glUniform3fv */
    /*  174 */  2819, /* glUniform3i */
    /*  175 */  2831, /* glUniform3iv */
    /*  176 */  2844, /* glUniform4f */
    /*  177 */  2856, /* glUniform4fv */
    /*  178 */  2869, /* glUniform4i */
    /*  179 */  2881, /* glUniform4iv */
    /*  180 */  2894, /* glUniformMatrix2fv */
    /*  181 */  2913, /* glUniformMatrix3fv */
    /*  182 */  2932, /* glUniformMatrix4fv */
    /*  183 */  2951, /* glUseProgram */
    /*  184 */  2964, /* glValidateProgram */
    /*  185 */  2982, /* glVertexAttrib1f */
    /*  186 */  2999, /* glVertexAttrib1fv */
    /*  187 */  3017, /* glVertexAttrib2f */
    /*  188 */  3034, /* glVertexAttrib2fv */
    /*  189 */  3052, /* glVertexAttrib3f */
    /*  190 */  3069, /* glVertexAttrib3fv */
    /*  191 */  3087, /* glVertexAttrib4f */
    /*  192 */  3104, /* glVertexAttrib4fv */
    /*  193 */  3122, /* glVertexAttribPointer */
    /*  194 */  3144, /* glDrawBuffers */
    /*  195 */  3158, /* glUniformMatrix2x3fv */
    /*  196 */  3179, /* glUniformMatrix2x4fv */
    /*  197 */  3200, /* glUniformMatrix3x2fv */
    /*  198 */  3221, /* glUniformMatrix3x4fv */
    /*  199 */  3242, /* glUniformMatrix4x2fv */
    /*  200 */  3263, /* glUniformMatrix4x3fv */
    /*  201 */  3284, /* glBeginConditionalRender */
    /*  202 */  3309, /* glBindFragDataLocation */
    /*  203 */  3332, /* glClampColor */
    /*  204 */  3345, /* glColorMaski */
    /*  205 */  3358, /* glDisablei */
    /*  206 */  3369, /* glEnablei */
    /*  207 */  3379, /* glEndConditionalRender */
    /*  208 */  3402, /* glFramebufferTexture1D */
    /*  209 */  3425, /* glFramebufferTexture3D */
    /*  210 */  3448, /* glGetBooleani_v */
    /*  211 */  3464, /* glGetTexParameterIiv */
    /*  212 */  3485, /* glGetTexParameterIuiv */
    /*  213 */  3507, /* glIsEnabledi */
    /*  214 */  3520, /* glTexParameterIiv */
    /*  215 */  3538, /* glTexParameterIuiv */
    /*  216 */  3557, /* glVertexAttribI1i */
    /*  217 */  3575, /* glVertexAttribI1iv */
    /*  218 */  3594, /* glVertexAttribI1ui */
    /*  219 */  3613, /* glVertexAttribI1uiv */
    /*  220 */  3633, /* glVertexAttribI2i */
    /*  221 */  3651, /* glVertexAttribI2iv */
    /*  222 */  3670, /* glVertexAttribI2ui */
    /*  223 */  3689, /* glVertexAttribI2uiv */
    /*  224 */  3709, /* glVertexAttribI3i */
    /*  225 */  3727, /* glVertexAttribI3iv */
    /*  226 */  3746, /* glVertexAttribI3ui */
    /*  227 */  3765, /* glVertexAttribI3uiv */
    /*  228 */  3785, /* glVertexAttribI4bv */
    /*  229 */  3804, /* glVertexAttribI4sv */
    /*  230 */  3823, /* glVertexAttribI4ubv */
    /*  231 */  3843, /* glVertexAttribI4usv */
    /*  232 */  3863, /* glBindBufferBase */
    /*  233 */  3880, /* glBindBufferRange */
    /*  234 */  3898, /* glGetIntegeri_v */
    /*  235 */  3914, /* glBindFramebuffer */
    /*  236 */  3932, /* glBindRenderbuffer */
    /*  237 */  3951, /* glCheckFramebufferStatus */
    /*  238 */  3976, /* glDeleteFramebuffers */
    /*  239 */  3997, /* glDeleteRenderbuffers */
    /*  240 */  4019, /* glFramebufferRenderbuffer */
    /*  241 */  4045, /* glFramebufferTexture2D */
    /*  242 */  4068, /* glGenFramebuffers */
    /*  243 */  4086, /* glGenRenderbuffers */
    /*  244 */  4105, /* glGenerateMipmap */
    /*  245 */  4122, /* glGetFramebufferAttachmentParameteriv */
    /*  246 */  4160, /* glGetRenderbufferParameteriv */
    /*  247 */  4189, /* glIsFramebuffer */
    /*  248 */  4205, /* glIsRenderbuffer */
    /*  249 */  4222, /* glRenderbufferStorage */
    /*  250 */  4244, /* glBeginTransformFeedback */
    /*  251 */  4269, /* glBindVertexArray */
    /*  252 */  4287, /* glBlitFramebuffer */
    /*  253 */  4305, /* glClearBufferfi */
    /*  254 */  4321, /* glClearBufferfv */
    /*  255 */  4337, /* glClearBufferiv */
    /*  256 */  4353, /* glClearBufferuiv */
    /*  257 */  4370, /* glDeleteVertexArrays */
    /*  258 */  4391, /* glEndTransformFeedback */
    /*  259 */  4414, /* glFlushMappedBufferRange */
    /*  260 */  4439, /* glFramebufferTextureLayer */
    /*  261 */  4465, /* glGenVertexArrays */
    /*  262 */  4483, /* glGetFragDataLocation */
    /*  263 */  4505, /* glGetStringi */
    /*  264 */  4518, /* glGetTransformFeedbackVarying */
    /*  265 */  4548, /* glGetUniformuiv */
    /*  266 */  4564, /* glGetVertexAttribIiv */
    /*  267 */  4585, /* glGetVertexAttribIuiv */
    /*  268 */  4607, /* glIsVertexArray */
    /*  269 */  4623, /* glMapBufferRange */
    /*  270 */  4640, /* glRenderbufferStorageMultisample */
    /*  271 */  4673, /* glTransformFeedbackVaryings */
    /*  272 */  4701, /* glUniform1ui */
    /*  273 */  4714, /* glUniform1uiv */
    /*  274 */  4728, /* glUniform2ui */
    /*  275 */  4741, /* glUniform2uiv */
    /*  276 */  4755, /* glUniform3ui */
    /*  277 */  4768, /* glUniform3uiv */
    /*  278 */  4782, /* glUniform4ui */
    /*  279 */  4795, /* glUniform4uiv */
    /*  280 */  4809, /* glVertexAttribI4i */
    /*  281 */  4827, /* glVertexAttribI4iv */
    /*  282 */  4846, /* glVertexAttribI4ui */
    /*  283 */  4865, /* glVertexAttribI4uiv */
    /*  284 */  4885, /* glVertexAttribIPointer */
    /*  285 */  4908, /* glGetActiveUniformName */
    /*  286 */  4931, /* glPrimitiveRestartIndex */
    /*  287 */  4955, /* glTexBuffer */
    /*  288 */  4967, /* glCopyBufferSubData */
    /*  289 */  4987, /* glDrawArraysInstanced */
    /*  290 */  5009, /* glDrawElementsInstanced */
    /*  291 */  5033, /* glGetActiveUniformBlockName */
    /*  292 */  5061, /* glGetActiveUniformBlockiv */
    /*  293 */  5087, /* glGetActiveUniformsiv */
    /*  294 */  5109, /* glGetUniformBlockIndex */
    /*  295 */  5132, /* glGetUniformIndices */
    /*  296 */  5152, /* glUniformBlockBinding */
    /*  297 */  5174, /* glDrawElementsBaseVertex */
    /*  298 */  5199, /* glDrawElementsInstancedBaseVertex */
    /*  299 */  5233, /* glDrawRangeElementsBaseVertex */
    /*  300 */  5263, /* glFramebufferTexture */
    /*  301 */  5284, /* glGetMultisamplefv */
    /*  302 */  5303, /* glMultiDrawElementsBaseVertex */
    /*  303 */  5333, /* glProvokingVertex */
    /*  304 */  5351, /* glSampleMaski */
    /*  305 */  5365, /* glTexImage2DMultisample */
    /*  306 */  5389, /* glTexImage3DMultisample */
    /*  307 */  5413, /* glClientWaitSync */
    /*  308 */  5430, /* glDeleteSync */
    /*  309 */  5443, /* glFenceSync */
    /*  310 */  5455, /* glGetBufferParameteri64v */
    /*  311 */  5480, /* glGetInteger64i_v */
    /*  312 */  5498, /* glGetInteger64v */
    /*  313 */  5514, /* glGetSynciv */
    /*  314 */  5526, /* glIsSync */
    /*  315 */  5535, /* glWaitSync */
    /*  316 */  5546, /* glBindFragDataLocationIndexed */
    /*  317 */  5576, /* glGetFragDataIndex */
    /*  318 */  5595, /* glGetQueryObjecti64v */
    /*  319 */  5616, /* glGetQueryObjectui64v */
    /*  320 */  5638, /* glGetSamplerParameterIiv */
    /*  321 */  5663, /* glGetSamplerParameterIuiv */
    /*  322 */  5689, /* glQueryCounter */
    /*  323 */  5704, /* glSamplerParameterIiv */
    /*  324 */  5726, /* glSamplerParameterIuiv */
    /*  325 */  5749, /* glVertexAttribP1ui */
    /*  326 */  5768, /* glVertexAttribP1uiv */
    /*  327 */  5788, /* glVertexAttribP2ui */
    /*  328 */  5807, /* glVertexAttribP2uiv */
    /*  329 */  5827, /* glVertexAttribP3ui */
    /*  330 */  5846, /* glVertexAttribP3uiv */
    /*  331 */  5866, /* glVertexAttribP4ui */
    /*  332 */  5885, /* glVertexAttribP4uiv */
    /*  333 */  5905, /* glBindSampler */
    /*  334 */  5919, /* glDeleteSamplers */
    /*  335 */  5936, /* glGenSamplers */
    /*  336 */  5950, /* glGetSamplerParameterfv */
    /*  337 */  5974, /* glGetSamplerParameteriv */
    /*  338 */  5998, /* glIsSampler */
    /*  339 */  6010, /* glSamplerParameterf */
    /*  340 */  6030, /* glSamplerParameterfv */
    /*  341 */  6051, /* glSamplerParameteri */
    /*  342 */  6071, /* glSamplerParameteriv */
    /*  343 */  6092, /* glVertexAttribDivisor */
    /*  344 */  6114, /* glClearDepthf */
    /*  345 */  6128, /* glDepthRangef */
    /*  346 */  6142, /* glGetShaderPrecisionFormat */
    /*  347 */  6169, /* glReleaseShaderCompiler */
    /*  348 */  6193, /* glShaderBinary */
    /*  349 */  6208, /* glBindTransformFeedback */
    /*  350 */  6232, /* glDeleteTransformFeedbacks */
    /*  351 */  6259, /* glGenTransformFeedbacks */
    /*  352 */  6283, /* glGetInternalformativ */
    /*  353 */  6305, /* glGetProgramBinary */
    /*  354 */  6324, /* glInvalidateFramebuffer */
    /*  355 */  6348, /* glInvalidateSubFramebuffer */
    /*  356 */  6375, /* glIsTransformFeedback */
    /*  357 */  6397, /* glPauseTransformFeedback */
    /*  358 */  6422, /* glProgramBinary */
    /*  359 */  6438, /* glProgramParameteri */
    /*  360 */  6458, /* glResumeTransformFeedback */
    /*  361 */  6484, /* glTexStorage2D */
    /*  362 */  6499, /* glTexStorage3D */
    /*  363 */  6514, /* glGetPointerv */
    /*  364 */  6528, /* glDebugMessageCallback */
    /*  365 */  6551, /* glDebugMessageCallbackKHR */
    /*  366 */  6577, /* glDebugMessageControl */
    /*  367 */  6599, /* glDebugMessageControlKHR */
    /*  368 */  6624, /* glDebugMessageInsert */
    /*  369 */  6645, /* glDebugMessageInsertKHR */
    /*  370 */  6669, /* glGetDebugMessageLog */
    /*  371 */  6690, /* glGetDebugMessageLogKHR */
    /*  372 */  6714, /* glGetObjectLabel */
    /*  373 */  6731, /* glGetObjectLabelKHR */
    /*  374 */  6751, /* glGetObjectPtrLabel */
    /*  375 */  6771, /* glGetObjectPtrLabelKHR */
    /*  376 */  6794, /* glGetPointervKHR */
    /*  377 */  6811, /* glObjectLabel */
    /*  378 */  6825, /* glObjectLabelKHR */
    /*  379 */  6842, /* glObjectPtrLabel */
    /*  380 */  6859, /* glObjectPtrLabelKHR */
    /*  381 */  6879, /* glPopDebugGroup */
    /*  382 */  6895, /* glPopDebugGroupKHR */
    /*  383 */  6914, /* glPushDebugGroup */
    /*  384 */  6931 /* glPushDebugGroupKHR */
};
/* ---- Extension hash table ------------------------------------------------
   One XXH3-64 hash per extension, in extArray index order.
   Pre-baked at generator time with the same algorithm used at load time. */
static const uint64_t kExtHashes_GL[] = {
    /*    0 */ 0xeafde92a9cccc4edULL, /* GL_EXT_texture_filter_anisotropic */
    /*    1 */ 0x5e0c5b9607ac8784ULL  /* GL_KHR_debug */
};

/* ---- Feature PFN range table ---------------------------------------------
 * Each entry maps one feature (by featArray index) to a contiguous run of
 * pfnArray slots. The loader iterates this table and bulk-loads the run
 * when featArray[entry.extension] is set.
 */
static const GloamPfnRange_t kFeatPfnRanges_GL[] = {
    {    0,    0,   48 }, /* GL_VERSION_1_0 */
    {    1,   48,   13 }, /* GL_VERSION_1_1 */
    {    1,  363,    1 }, /* GL_VERSION_1_1 */
    {    2,   61,    4 }, /* GL_VERSION_1_2 */
    {    3,   65,    9 }, /* GL_VERSION_1_3 */
    {    4,   74,    9 }, /* GL_VERSION_1_4 */
    {    5,   83,   19 }, /* GL_VERSION_1_5 */
    {    6,  102,   93 }, /* GL_VERSION_2_0 */
    {    7,  195,    6 }, /* GL_VERSION_2_1 */
    {    8,  201,   84 }, /* GL_VERSION_3_0 */
    {    9,  232,    3 }, /* GL_VERSION_3_1 */
    {    9,  285,   12 }, /* GL_VERSION_3_1 */
    {   10,  297,   19 }, /* GL_VERSION_3_2 */
    {   11,  316,   28 }, /* GL_VERSION_3_3 */
    {   12,   12,   35 }, /* GL_ES_VERSION_2_0 */
    {   12,   51,   10 }, /* GL_ES_VERSION_2_0 */
    {   12,   68,    4 }, /* GL_ES_VERSION_2_0 */
    {   12,   80,    3 }, /* GL_ES_VERSION_2_0 */
    {   12,   86,    7 }, /* GL_ES_VERSION_2_0 */
    {   12,  131,   63 }, /* GL_ES_VERSION_2_0 */
    {   12,  235,   15 }, /* GL_ES_VERSION_2_0 */
    {   12,  344,    5 }, /* GL_ES_VERSION_2_0 */
    {   13,   47,    1 }, /* GL_ES_VERSION_3_0 */
    {   13,   61,    4 }, /* GL_ES_VERSION_3_0 */
    {   13,   72,    2 }, /* GL_ES_VERSION_3_0 */
    {   13,   93,    9 }, /* GL_ES_VERSION_3_0 */
    {   13,  194,    7 }, /* GL_ES_VERSION_3_0 */
    {   13,  232,    3 }, /* GL_ES_VERSION_3_0 */
    {   13,  250,   35 }, /* GL_ES_VERSION_3_0 */
    {   13,  288,    9 }, /* GL_ES_VERSION_3_0 */
    {   13,  307,    9 }, /* GL_ES_VERSION_3_0 */
    {   13,  333,   11 }, /* GL_ES_VERSION_3_0 */
    {   13,  349,   14 }, /* GL_ES_VERSION_3_0 */
};

/* ---- PFN range helper (GL / EGL / GLX / WGL) ----------------------------
 * Walks a contiguous run of pfnArray slots and calls the plain load callback
 * (name only) for each one.
 */
static void gloam_load_pfn_range_gl(GloamGLContext *context, GloamLoadFunc getProcAddr, uint16_t start, uint16_t count)
{
    uint16_t i;
    for (i = start; i < (uint16_t)(start + count); ++i) {
        const char *pfnName = &kFnNameData_GL[kFnNameOffsets_GL[i]];
        context->pfnArray[i] = (void *)getProcAddr(pfnName);
    }
}

/* ---- Alias resolution table ----------------------------------------------
 * Pairs are sorted by canonical index so same-canonical entries are
 * consecutive; the resolver processes them in a single forward pass.
 */
static const GloamAliasPair_t kAliases_GL[] = {
    {  363,  376 }, /* glGetPointerv and glGetPointervKHR */
    {  364,  365 }, /* glDebugMessageCallback and glDebugMessageCallbackKHR */
    {  366,  367 }, /* glDebugMessageControl and glDebugMessageControlKHR */
    {  368,  369 }, /* glDebugMessageInsert and glDebugMessageInsertKHR */
    {  370,  371 }, /* glGetDebugMessageLog and glGetDebugMessageLogKHR */
    {  372,  373 }, /* glGetObjectLabel and glGetObjectLabelKHR */
    {  374,  375 }, /* glGetObjectPtrLabel and glGetObjectPtrLabelKHR */
    {  377,  378 }, /* glObjectLabel and glObjectLabelKHR */
    {  379,  380 }, /* glObjectPtrLabel and glObjectPtrLabelKHR */
    {  381,  382 }, /* glPopDebugGroup and glPopDebugGroupKHR */
    {  383,  384 }, /* glPushDebugGroup and glPushDebugGroupKHR */
};

GLOAM_NO_INLINE static void gloam_resolve_aliases_gl(GloamGLContext *context)
{
    uint32_t i;
    for (i = 0; i < GLOAM_ARRAYSIZE(kAliases_GL); ++i) {
        uint16_t ci = kAliases_GL[i].first;
        uint16_t si = kAliases_GL[i].second;
        if (!context->pfnArray[ci] && context->pfnArray[si])
            context->pfnArray[ci] = context->pfnArray[si];
        else if (context->pfnArray[ci] && !context->pfnArray[si])
            context->pfnArray[si] = context->pfnArray[ci];
    }
}

/* ==========================================================================
 * Driver extension query (shared across per-API sections)
 * ==========================================================================
 */

/* Query driver-reported extension names, hash them, and fill *out_exts.
 * Returns 1 on success, 0 on failure. Caller must free(*out_exts).
 */
static int gloam_gl_get_extensions(GloamGLContext *context, uint64_t **out_exts, uint32_t *out_num_exts)
{
#if defined(GL_ES_VERSION_3_0) || defined(GL_VERSION_3_0)
    /* Modern path: glGetIntegerv(GL_NUM_EXTENSIONS) + glGetStringi. */
    if (context->GetStringi != NULL && context->GetIntegerv != NULL) {
        GLint n = 0;
        uint32_t num_exts, i;
        uint64_t *exts;
        context->GetIntegerv(GL_NUM_EXTENSIONS, &n);
        num_exts = (uint32_t)n;
        if (num_exts == 0) {
            *out_exts = NULL;
            *out_num_exts = 0;
            return 1;
        }
        exts = (uint64_t *)calloc(num_exts, sizeof(uint64_t));
        if (!exts)
            return 0;
        for (i = 0; i < num_exts; ++i) {
            const char *name = (const char *)context->GetStringi(GL_EXTENSIONS, i);
            if (name)
                exts[i] = gloam_hash_string(name, strlen(name));
        }
        gloam_sort_hashes(exts, num_exts);
        *out_exts     = exts;
        *out_num_exts = num_exts;
        return 1;
    }
#endif
    /* Legacy path: glGetString(GL_EXTENSIONS) — space-separated string. */
    {
        const char *ext_str;
        if (!context->GetString)
            return 0;
        ext_str = (const char *)context->GetString(GL_EXTENSIONS);
        if (!ext_str)
            return 0;
        return gloam_hash_ext_string(ext_str, out_exts, out_num_exts);
    }
}

/* ==========================================================================
 * Per-API sections
 * ==========================================================================
 */

/* --------------------------------------------------------------------------
 * API: gl
 * --------------------------------------------------------------------------
 */

/* Extension index subset for gl: extArray indices this API supports. */
static const uint16_t kExtIdx_gl[] = {
       0, /* GL_EXT_texture_filter_anisotropic */
       1, /* GL_KHR_debug */
};

/* Extension PFN range table for gl. */
static const GloamPfnRange_t kExtPfnRanges_gl[] = {
    {    1,  363,    2 }, /* GL_KHR_debug */
    {    1,  366,    1 }, /* GL_KHR_debug */
    {    1,  368,    1 }, /* GL_KHR_debug */
    {    1,  370,    1 }, /* GL_KHR_debug */
    {    1,  372,    1 }, /* GL_KHR_debug */
    {    1,  374,    1 }, /* GL_KHR_debug */
    {    1,  377,    1 }, /* GL_KHR_debug */
    {    1,  379,    1 }, /* GL_KHR_debug */
    {    1,  381,    1 }, /* GL_KHR_debug */
    {    1,  383,    1 }, /* GL_KHR_debug */
};

/* Search pre-baked kExtHashes_GL against the sorted driver hash list and set
 * extArray flags for every matching extension.
 */
static int gloam_gl_find_extensions_gl(GloamGLContext *context)
{
    uint64_t *exts = NULL;
    uint32_t  num_exts = 0, i;

    if (!gloam_gl_get_extensions(context, &exts, &num_exts))
        return 0;

    for (i = 0; i < GLOAM_ARRAYSIZE(kExtIdx_gl); ++i) {
        const uint16_t extIdx = kExtIdx_gl[i];
        context->extArray[extIdx] = (unsigned char)gloam_hash_search(exts, num_exts, kExtHashes_GL[extIdx]);
    }

    free(exts);
    return 1;
}

/* Parse the GL_VERSION string and set featArray entries for this API. */
static int gloam_gl_find_core_gl(GloamGLContext *context)
{
    int i, major = 0, minor = 0;
    unsigned short version_value;
    static const char * const kPrefixes[] = {
        "OpenGL ES-CM ", "OpenGL ES-CL ", "OpenGL ES ",
        "OpenGL SC ",    "OpenGL ",       NULL
    };
    const char *version = (const char *)context->GetString(GL_VERSION);
    if (!version)
        return 0;
    for (i = 0; kPrefixes[i]; ++i) {
        const size_t len = strlen(kPrefixes[i]);
        if (strncmp(version, kPrefixes[i], len) == 0) {
            version += len;
            break;
        }
    }
    GLOAM_IMPL_UTIL_SSCANF(version, "%d.%d", &major, &minor);
    version_value = (unsigned short)((major << 8) | minor);

    context->VERSION_1_0 = (unsigned char)(version_value >= 0x0100);
    context->VERSION_1_1 = (unsigned char)(version_value >= 0x0101);
    context->VERSION_1_2 = (unsigned char)(version_value >= 0x0102);
    context->VERSION_1_3 = (unsigned char)(version_value >= 0x0103);
    context->VERSION_1_4 = (unsigned char)(version_value >= 0x0104);
    context->VERSION_1_5 = (unsigned char)(version_value >= 0x0105);
    context->VERSION_2_0 = (unsigned char)(version_value >= 0x0200);
    context->VERSION_2_1 = (unsigned char)(version_value >= 0x0201);
    context->VERSION_3_0 = (unsigned char)(version_value >= 0x0300);
    context->VERSION_3_1 = (unsigned char)(version_value >= 0x0301);
    context->VERSION_3_2 = (unsigned char)(version_value >= 0x0302);
    context->VERSION_3_3 = (unsigned char)(version_value >= 0x0303);

    return (int)version_value;
}

int gloamLoadGLContext(GloamGLContext *context, GloamLoadFunc getProcAddr)
{
    int version;
    uint32_t i;
    GLOAM_UNUSED(kFnCount_GL);

    memset(context, 0, sizeof(*context));

    /* Bootstrap: glGetString must be loaded before find_core can run. */
    context->GetString = (PFNGLGETSTRINGPROC)getProcAddr("glGetString");
    if (!context->GetString)
        return 0;

    version = gloam_gl_find_core_gl(context);
    if (!version)
        return 0;

    /* Load PFNs for each enabled feature via the range table. */
    for (i = 0; i < GLOAM_ARRAYSIZE(kFeatPfnRanges_GL); ++i) {
        const GloamPfnRange_t *r = &kFeatPfnRanges_GL[i];
        if (context->featArray[r->extension])
            gloam_load_pfn_range_gl(context, getProcAddr, r->start, r->count);
    }

    if (!gloam_gl_find_extensions_gl(context))
        return 0;

    /* Load PFNs for each detected extension via the range table. */
    for (i = 0; i < GLOAM_ARRAYSIZE(kExtPfnRanges_gl); ++i) {
        const GloamPfnRange_t *r = &kExtPfnRanges_gl[i];
        if (context->extArray[r->extension])
            gloam_load_pfn_range_gl(context, getProcAddr, r->start, r->count);
    }

    gloam_resolve_aliases_gl(context);

    return version;
}

int gloamLoadGL(GloamLoadFunc getProcAddr)
{
    return gloamLoadGLContext(&gloam_gl_context, getProcAddr);
}


/* --------------------------------------------------------------------------
 * API: gles2
 * --------------------------------------------------------------------------
 */

/* Extension index subset for gles2: extArray indices this API supports. */
static const uint16_t kExtIdx_gles2[] = {
       0, /* GL_EXT_texture_filter_anisotropic */
       1, /* GL_KHR_debug */
};

/* Extension PFN range table for gles2. */
static const GloamPfnRange_t kExtPfnRanges_gles2[] = {
    {    1,  365,    1 }, /* GL_KHR_debug */
    {    1,  367,    1 }, /* GL_KHR_debug */
    {    1,  369,    1 }, /* GL_KHR_debug */
    {    1,  371,    1 }, /* GL_KHR_debug */
    {    1,  373,    1 }, /* GL_KHR_debug */
    {    1,  375,    2 }, /* GL_KHR_debug */
    {    1,  378,    1 }, /* GL_KHR_debug */
    {    1,  380,    1 }, /* GL_KHR_debug */
    {    1,  382,    1 }, /* GL_KHR_debug */
    {    1,  384,    1 }, /* GL_KHR_debug */
};

/* Search pre-baked kExtHashes_GL against the sorted driver hash list and set
 * extArray flags for every matching extension.
 */
static int gloam_gl_find_extensions_gles2(GloamGLContext *context)
{
    uint64_t *exts = NULL;
    uint32_t  num_exts = 0, i;

    if (!gloam_gl_get_extensions(context, &exts, &num_exts))
        return 0;

    for (i = 0; i < GLOAM_ARRAYSIZE(kExtIdx_gles2); ++i) {
        const uint16_t extIdx = kExtIdx_gles2[i];
        context->extArray[extIdx] = (unsigned char)gloam_hash_search(exts, num_exts, kExtHashes_GL[extIdx]);
    }

    free(exts);
    return 1;
}

/* Parse the GL_VERSION string and set featArray entries for this API. */
static int gloam_gl_find_core_gles2(GloamGLContext *context)
{
    int i, major = 0, minor = 0;
    unsigned short version_value;
    static const char * const kPrefixes[] = {
        "OpenGL ES-CM ", "OpenGL ES-CL ", "OpenGL ES ",
        "OpenGL SC ",    "OpenGL ",       NULL
    };
    const char *version = (const char *)context->GetString(GL_VERSION);
    if (!version)
        return 0;
    for (i = 0; kPrefixes[i]; ++i) {
        const size_t len = strlen(kPrefixes[i]);
        if (strncmp(version, kPrefixes[i], len) == 0) {
            version += len;
            break;
        }
    }
    GLOAM_IMPL_UTIL_SSCANF(version, "%d.%d", &major, &minor);
    version_value = (unsigned short)((major << 8) | minor);

    context->ES_VERSION_2_0 = (unsigned char)(version_value >= 0x0200);
    context->ES_VERSION_3_0 = (unsigned char)(version_value >= 0x0300);

    return (int)version_value;
}

int gloamLoadGLES2Context(GloamGLContext *context, GloamLoadFunc getProcAddr)
{
    int version;
    uint32_t i;
    GLOAM_UNUSED(kFnCount_GL);

    memset(context, 0, sizeof(*context));

    /* Bootstrap: glGetString must be loaded before find_core can run. */
    context->GetString = (PFNGLGETSTRINGPROC)getProcAddr("glGetString");
    if (!context->GetString)
        return 0;

    version = gloam_gl_find_core_gles2(context);
    if (!version)
        return 0;

    /* Load PFNs for each enabled feature via the range table. */
    for (i = 0; i < GLOAM_ARRAYSIZE(kFeatPfnRanges_GL); ++i) {
        const GloamPfnRange_t *r = &kFeatPfnRanges_GL[i];
        if (context->featArray[r->extension])
            gloam_load_pfn_range_gl(context, getProcAddr, r->start, r->count);
    }

    if (!gloam_gl_find_extensions_gles2(context))
        return 0;

    /* Load PFNs for each detected extension via the range table. */
    for (i = 0; i < GLOAM_ARRAYSIZE(kExtPfnRanges_gles2); ++i) {
        const GloamPfnRange_t *r = &kExtPfnRanges_gles2[i];
        if (context->extArray[r->extension])
            gloam_load_pfn_range_gl(context, getProcAddr, r->start, r->count);
    }

    gloam_resolve_aliases_gl(context);

    return version;
}

int gloamLoadGLES2(GloamLoadFunc getProcAddr)
{
    return gloamLoadGLES2Context(&gloam_gl_context, getProcAddr);
}
