[workspace]
git_release_enable = true
git_release_name = "{{ version }}"
git_tag_enable = true
git_tag_name = "{{ version }}"
pr_branch_prefix = "release/"
pr_draft = true
pr_labels = ["release"]
release_always = true
