//! Layout oracle: cross-checks the Rust backend's type layouts against the C
//! backend's, using a C compiler as the arbiter.
//!
//! The Rust side of the truth comes from the generated crate itself: the
//! `--layout-probe` binary prints the size, alignment, and field offsets of
//! every emitted type (as compiled by rustc for the host).  Those facts are
//! then turned into a C translation unit full of `_Static_assert`s against
//! the C backend's generated header for the same configuration, and compiled
//! (compile-only — a mismatch fails compilation naming the exact type and
//! member).  This mechanically validates the hand-audited ABI scalar map,
//! the `#[repr(C)]` struct/union emission, and the bitfield carrier merging.
//!
//! The test needs cargo (to build the probe) and a C compiler (found the
//! same way the other compile checks find one); it skips with a note when
//! either is unavailable.

mod common;
use common::{generate, generate_rust};

/// A configuration rich in layout hazards: structs with arrays and nested
/// records, unions, the bitfield structs (VK_KHR_acceleration_structure),
/// dispatchable + non-dispatchable handles, 64-bit enum carriers, and — via
/// video decode — by-value `StdVideo*` enum members (the Rust side declares
/// them `i32`; the C side gets the real enums from the bundled vk_video
/// headers, so the asserts pin that assumption and every member offset
/// downstream of it).  No platform-protected extensions: the C side would
/// need `VK_USE_PLATFORM_*` defines and platform headers (the probe skips
/// protected types for the same reason).
const VK_ARGS: &[&str] = &[
    "--api",
    "vk=1.3",
    "--extensions",
    "VK_KHR_swapchain,VK_KHR_get_physical_device_properties2,VK_EXT_debug_utils,\
     VK_KHR_acceleration_structure,VK_KHR_deferred_host_operations,\
     VK_KHR_video_decode_h264",
];

#[test]
fn layout_oracle_vk() {
    // Rust side: generate the crate with the layout probe and run it.
    let rust_dir = generate_rust(VK_ARGS, &["--layout-probe"]);
    let output = match std::process::Command::new("cargo")
        .args(["run", "--quiet", "--bin", "layout_probe"])
        .current_dir(rust_dir.path())
        .output()
    {
        Ok(o) => o,
        Err(e) => {
            eprintln!("layout oracle skipped: could not spawn cargo: {e}");
            return;
        }
    };
    assert!(
        output.status.success(),
        "layout probe failed to build or run — the probe is generated from \
         the same emission pass as the types, so this indicates emitter \
         drift:\n{}",
        String::from_utf8_lossy(&output.stderr)
    );
    let facts = String::from_utf8(output.stdout).expect("probe output is UTF-8");
    let n_facts = facts.lines().filter(|l| !l.trim().is_empty()).count();
    assert!(
        n_facts >= 1000,
        "suspiciously few layout facts ({n_facts}) — probe coverage collapsed?"
    );

    // C side: generate the loader for the same configuration and compile a
    // TU asserting every fact against the generated header.
    let c_dir = generate(VK_ARGS, &[]);
    let oracle_c = build_oracle_c(&facts);
    let oracle_path = c_dir.path().join("src").join("layout_oracle.c");
    std::fs::write(&oracle_path, &oracle_c).unwrap();

    let target = env!("TARGET");
    let mut build = cc::Build::new();
    build
        .target(target)
        .host(target)
        .opt_level(0)
        .out_dir(c_dir.path().join("src"))
        .include(c_dir.path().join("include"))
        .warnings(false)
        .cargo_warnings(false)
        .std("c11")
        .file(&oracle_path);

    if let Err(e) = build.try_compile("gloam_layout_oracle") {
        let msg = e.to_string();
        if msg.contains("Failed to find tool")
            || msg.contains("not found")
            || msg.contains("couldn't find")
        {
            eprintln!("layout oracle skipped: no C compiler found");
            return;
        }
        panic!(
            "LAYOUT MISMATCH between the Rust and C backends (or the oracle \
             TU failed to compile) — each failing _Static_assert names the \
             divergent type/member:\n{msg}"
        );
    }
    eprintln!("layout oracle: {n_facts} facts verified against the C header");
}

/// Turn the probe's `size`/`align`/`offset` lines into a C translation unit
/// of `_Static_assert`s against the generated header.
fn build_oracle_c(facts: &str) -> String {
    let mut s = String::with_capacity(facts.len() * 4);
    s.push_str(
        "/* @generated by gloam's layout-oracle test.  Each assert pins one\n\
         \x20* layout fact reported by the generated Rust crate's layout probe. */\n\
         #include <stddef.h>\n\
         #include <gloam/vk.h>\n\n\
         #if defined(_MSC_VER) && !defined(__clang__)\n\
         #  define GLOAM_ALIGNOF __alignof\n\
         #else\n\
         #  define GLOAM_ALIGNOF _Alignof\n\
         #endif\n\n",
    );
    for line in facts.lines() {
        let parts: Vec<&str> = line.split_whitespace().collect();
        match parts.as_slice() {
            ["size", ty, n] => {
                s.push_str(&format!(
                    "_Static_assert(sizeof({ty}) == {n}, \"sizeof {ty}\");\n"
                ));
            }
            ["align", ty, n] => {
                s.push_str(&format!(
                    "_Static_assert(GLOAM_ALIGNOF({ty}) == {n}, \"alignof {ty}\");\n"
                ));
            }
            ["offset", ty, member, n] => {
                s.push_str(&format!(
                    "_Static_assert(offsetof({ty}, {member}) == {n}, \"offsetof {ty}.{member}\");\n"
                ));
            }
            [] => {}
            other => panic!("unrecognized probe line: {other:?}"),
        }
    }
    s
}
