//! Rust loader generator.
//!
//! Emits a self-contained crate — `Cargo.toml`, an `#![no_std]` `lib.rs`, and
//! one module per resolved spec (`src/gl.rs`, `src/egl.rs`, `src/vk.rs`,
//! `src/wgl.rs`, `src/glx.rs` — mirroring the C backend's per-spec `.c`/`.h`
//! files in a shared tree).  Every spec family the C backend generates is
//! covered.
//!
//! This module owns the crate-level orchestration: `generate()` dispatches
//! each feature set to its spec's emitter and assembles the crate scaffolding.
//! The pieces live in:
//!
//! - [`abi`] — the ABI scalar map and `TypeRef` → Rust type printers, plus
//!   the derived base-type emitter (shared by every spec).
//! - [`common`] — spec-agnostic table/dispatch emission (name blob, PFN
//!   ranges, XXH3 extension tables, dispatch methods, presence queries).
//! - [`gl_loader`] / [`egl_loader`] / [`vk_loader`] / [`wgl_loader`] /
//!   [`glx_loader`] — per-spec load flows, each mirroring its C
//!   counterpart's contract.
//! - [`vk_types`] — the Vulkan type printer (structs, unions, handles,
//!   enum groups) over the structured registry payloads.
//!
//! Generated-output conventions shared by every module: hand-formatted tables
//! carry `#[rustfmt::skip]`; unsafe operations sit in explicit `unsafe {}`
//! blocks (`#![deny(unsafe_op_in_unsafe_fn)]`), so the output is valid under
//! any edition — the pinned `edition = 2021` is a stable default, not
//! load-bearing.

mod abi;
mod common;
mod egl_loader;
mod gl_loader;
mod glx_loader;
mod vk_loader;
mod vk_types;
mod wgl_loader;

use std::fmt::Write as _;
use std::path::Path;

use anyhow::{Context, Result, bail};
use indexmap::IndexMap;

use super::GeneratedTree;
use crate::identity::Spec;
use crate::preamble;
use crate::provenance::load::SourceStore;
use crate::provenance::manifest::{OutputEntry, ProvenancePin, git_blob_sha1};
use crate::resolve::FeatureSet;

/// Generate one crate covering every resolved feature set: one module file
/// per spec (`src/gl.rs`, `src/egl.rs`, `src/vk.rs` — mirroring the C
/// backend's per-spec `.c`/`.h` files in a shared tree), a `lib.rs` carrying
/// the crate-level attributes and module declarations, and a single
/// `Cargo.toml` whose name joins the spec stems and whose features are the
/// union of every module's needs.  A single-spec crate re-exports its module
/// at the root (`gloam_gl::Gl` and `gloam_gl::gl::Gl` both resolve); a
/// multi-spec crate does not, because loader types collide across modules
/// (each has its own `LoadError`).
pub fn generate(
    feature_sets: &[FeatureSet],
    args: &crate::cli::RustArgs,
    out: &Path,
    store: &SourceStore,
    command_line: &str,
) -> Result<GeneratedTree> {
    if args.mx_global
        && !feature_sets
            .iter()
            .any(|fs| matches!(fs.spec, Spec::Gl | Spec::Vk))
    {
        bail!("--mx-global is only implemented for the GL and Vulkan rust backends");
    }

    let mut pins: IndexMap<String, ProvenancePin> = IndexMap::new();
    let mut files: Vec<OutputEntry> = Vec::new();
    let mut all_source_keys: Vec<String> = Vec::new();
    let mut platform_features: Vec<String> = Vec::new();
    let mut probe_facts: Vec<(String, Vec<vk_types::ProbeEntry>)> = Vec::new();
    let mut lib_rs = String::from(
        "// @generated by gloam.  One module per generated API; see each\n\
         // module's header for its full provenance.\n\
         #![no_std]\n\n",
    );

    let src_dir = out.join("src");
    std::fs::create_dir_all(&src_dir)?;

    for fs in feature_sets {
        let stem = output_stem(fs);

        // Provenance pins for every contributing source (same as the C
        // backend); sets sharing a source agree on the pin by construction.
        let source_key_refs: Vec<&str> = fs.source_keys.iter().map(String::as_str).collect();
        pins.extend(
            store
                .resolve(&source_key_refs)
                .context("resolving source provenance")?
                .into_iter()
                .map(|(key, src)| (key, src.pin)),
        );
        all_source_keys.extend(fs.source_keys.iter().cloned());

        let fs_pins: IndexMap<String, ProvenancePin> = fs
            .source_keys
            .iter()
            .filter_map(|k| pins.get(k).map(|p| (k.clone(), p.clone())))
            .collect();
        let preamble = rustify_preamble(&preamble::build_preamble(fs, &fs_pins, command_line));
        let body = match fs.spec {
            Spec::Vk => {
                let (body, entries) = vk_loader::emit_vk_module(fs, &preamble, args.mx_global)?;
                probe_facts.push((stem.clone(), entries));
                normalize_eof(body)
            }
            Spec::Egl => normalize_eof(egl_loader::emit_egl_module(fs, &preamble)?),
            Spec::Wgl => normalize_eof(wgl_loader::emit_wgl_module(fs, &preamble)?),
            Spec::Glx => normalize_eof(glx_loader::emit_glx_module(fs, &preamble)?),
            Spec::Gl => normalize_eof(gl_loader::emit_gl_module(fs, &preamble, args.mx_global)?),
        };

        let module_path = format!("src/{stem}.rs");
        std::fs::write(out.join(&module_path), &body)?;
        files.push(OutputEntry {
            path: module_path,
            blob: git_blob_sha1(body.as_bytes()),
            verbatim: false,
            derived_from: fs.source_keys.clone(),
        });
        if let Some(cfg) = module_cfg(fs.spec) {
            let _ = writeln!(lib_rs, "#[cfg({cfg})]");
        }
        let _ = writeln!(lib_rs, "pub mod {stem};");

        // One cargo feature per platform-protection macro appearing anywhere
        // in the build; the guarded items carry matching #[cfg(feature)]
        // attributes.  Vulkan-only: the other backends emit no guards.
        if fs.spec == Spec::Vk {
            platform_features.extend(
                fs.types
                    .iter()
                    .flat_map(|t| t.protect.0.iter())
                    .chain(fs.extensions.iter().flat_map(|e| e.protect.0.iter()))
                    .chain(fs.commands.iter().flat_map(|c| c.protect.0.iter()))
                    .cloned(),
            );
        }
    }

    // Single-spec convenience: the crate root re-exports the one module, so
    // `gloam_gl::Gl` keeps working.
    if let [fs] = feature_sets {
        if let Some(cfg) = module_cfg(fs.spec) {
            let _ = writeln!(lib_rs, "#[cfg({cfg})]");
        }
        let _ = writeln!(lib_rs, "pub use self::{}::*;", output_stem(fs));
    }

    if feature_sets.iter().any(|fs| fs.spec == Spec::Vk) {
        lib_rs.push_str(
            "#[cfg(feature = \"alloc\")]
extern crate alloc;
",
        );
    }

    platform_features.sort_unstable();
    platform_features.dedup();
    let stems: Vec<String> = feature_sets.iter().map(output_stem).collect();
    let crate_name = format!("gloam_{}", stems.join("_"));

    if args.layout_probe {
        let probe_rs = emit_layout_probe(&crate_name, &probe_facts);
        let bin_dir = src_dir.join("bin");
        std::fs::create_dir_all(&bin_dir)?;
        std::fs::write(bin_dir.join("layout_probe.rs"), &probe_rs)?;
        files.push(OutputEntry {
            path: "src/bin/layout_probe.rs".to_string(),
            blob: git_blob_sha1(probe_rs.as_bytes()),
            verbatim: false,
            derived_from: Vec::new(),
        });
    }

    let has_vk = feature_sets.iter().any(|fs| fs.spec == Spec::Vk);
    let cargo_toml = emit_cargo_toml(&crate_name, &platform_features, has_vk);
    let rustfmt_toml = emit_rustfmt_toml();
    std::fs::write(out.join("Cargo.toml"), &cargo_toml)?;
    std::fs::write(out.join("rustfmt.toml"), &rustfmt_toml)?;
    std::fs::write(src_dir.join("lib.rs"), &lib_rs)?;

    all_source_keys.sort_unstable();
    all_source_keys.dedup();
    files.insert(
        0,
        OutputEntry {
            path: "Cargo.toml".to_string(),
            blob: git_blob_sha1(cargo_toml.as_bytes()),
            verbatim: false,
            derived_from: Vec::new(),
        },
    );
    files.insert(
        1,
        OutputEntry {
            path: "src/lib.rs".to_string(),
            blob: git_blob_sha1(lib_rs.as_bytes()),
            verbatim: false,
            derived_from: all_source_keys,
        },
    );

    Ok(GeneratedTree { pins, files })
}

/// Emit the generated loader crate's `Cargo.toml`.  The pinned `edition = 2021`
/// is a conservative default (the code uses explicit `unsafe {}` blocks, so any
/// edition works); the crate encapsulates the `xxhash-rust` dependency it uses
/// for extension-name hashing.  `platform_features` declares one cargo feature
/// per platform-protection macro (the Rust analogue of Vulkan's
/// `VK_USE_PLATFORM_*` defines); empty for the GL family.  Vulkan crates gain
/// a default-on `alloc` feature gating the heap-using discovery loader.
fn emit_cargo_toml(crate_name: &str, platform_features: &[String], has_vk: bool) -> String {
    let mut features = String::new();
    if has_vk {
        features.push_str(
            "# Heap-using conveniences: Vulkan's discover() needs enumeration\n\
             # buffers.  Disable (default-features = false) for allocator-free\n\
             # builds; the phased loaders never allocate.\n\
             alloc = []\n",
        );
    }
    if !platform_features.is_empty() {
        features.push_str(
            "# Platform-windowing surface opt-ins, mirroring the C headers'\n\
             # VK_USE_PLATFORM_* defines.\n",
        );
        for f in platform_features {
            let _ = writeln!(features, "{f} = []");
        }
    }
    let default = if has_vk {
        "default = [\"alloc\"]\n"
    } else {
        ""
    };
    format!(
        "# @generated by gloam.\n\
         [package]\n\
         name = \"{crate_name}\"\n\
         version = \"0.0.0\"\n\
         edition = \"2021\"\n\
         # c\"...\" literals need 1.77; core::error::Error needs 1.81.\n\
         rust-version = \"1.81\"\n\
         \n\
         [features]\n\
         {default}\
         # Analogue of a KHR_no_error GL context, applied at compile time:\n\
         # removes the per-call is-loaded check, so calling an unloaded\n\
         # function is undefined behavior (as in C) instead of a panic.\n\
         no-error = []\n\
         {features}\
         \n\
         [dependencies]\n\
         xxhash-rust = {{ version = \"0.8\", features = [\"xxh3\"] }}\n"
    )
}

/// Emit the generated loader crate's `rustfmt.toml`. This file directs rustfmt
/// to not re-format the generated lib.rs code.
fn emit_rustfmt_toml() -> String {
    "# @generated by gloam.\n\
         format_generated_files = false\n"
        .to_string()
}

/// Emit `src/bin/layout_probe.rs` (the `--layout-probe` flag): a binary that
/// prints one `size`/`align`/`offset` fact per line for every type the crate
/// emitted, keyed by the *C* spelling of each member name, so the
/// layout-oracle test can turn the output into C `_Static_assert`s against
/// the C backend's header for the same configuration.  Types are spelled
/// fully qualified, so identically named types in different spec modules can
/// never collide.
fn emit_layout_probe(crate_name: &str, facts: &[(String, Vec<vk_types::ProbeEntry>)]) -> String {
    let mut s = String::with_capacity(256 * 1024);
    s.push_str(
        "// @generated by gloam.  Layout probe: prints the size, alignment, and\n\
         // field offsets of every emitted type, for gloam's layout-oracle test.\n\n\
         fn main() {\n",
    );
    for (stem, entries) in facts {
        for e in entries {
            let ty = format!("{crate_name}::{stem}::{}", e.name);
            let _ = writeln!(
                s,
                "    println!(\"size {} {{}}\", core::mem::size_of::<{ty}>());",
                e.name
            );
            let _ = writeln!(
                s,
                "    println!(\"align {} {{}}\", core::mem::align_of::<{ty}>());",
                e.name
            );
            for (c_name, rust_field) in &e.fields {
                let _ = writeln!(
                    s,
                    "    println!(\"offset {} {c_name} {{}}\", core::mem::offset_of!({ty}, {rust_field}));",
                    e.name
                );
            }
        }
    }
    s.push_str("}\n");
    s
}

/// The `cfg` predicate gating a spec's module in `lib.rs`, for specs whose
/// platform types only exist on one OS family (the analogue of the C
/// backend's `#ifdef GLOAM_PLATFORM_*` around the whole translation unit).
/// `None` = unconditional.
fn module_cfg(spec: Spec) -> Option<&'static str> {
    match spec {
        Spec::Wgl => Some("windows"),
        // Mirrors the C output's GLOAM_PLATFORM_LINUX (`defined(__linux)`).
        Spec::Glx => Some("target_os = \"linux\""),
        _ => None,
    }
}

/// Merged builds use the spec name (`gl`); non-merged use the single API name.
fn output_stem(fs: &FeatureSet) -> String {
    if fs.is_merged {
        fs.spec_name.clone()
    } else {
        fs.apis
            .first()
            .cloned()
            .unwrap_or_else(|| fs.spec_name.clone())
    }
}

/// Turn the C block-comment preamble (`/* ... */` with ` * ` line prefixes)
/// into Rust line comments.  Converting the rendered C comment keeps
/// `build_preamble` single-format; worth teaching it to yield raw lines
/// only if a third output language ever appears.
fn rustify_preamble(c_preamble: &str) -> String {
    let mut out = String::new();
    for line in c_preamble.lines() {
        let t = line.trim_end();
        if t == "/*" || t == " */" {
            continue;
        }
        let rest = t.strip_prefix(" *").unwrap_or(t);
        let _ = writeln!(out, "//{rest}");
    }
    out
}

/// Rendered files end with exactly one newline.
fn normalize_eof(mut rendered: String) -> String {
    rendered.truncate(rendered.trim_end_matches('\n').len());
    rendered.push('\n');
    rendered
}
