//! Build-time version and git metadata.
//!
//! Constants are generated by `build.rs` and embedded at compile time.
//! When built from a crates.io tarball (no `.git` directory), only
//! `PKG_VERSION` and `VERSION` are populated — all git fields are `None`.
//!
//! Not all constants are used today — they exist so downstream code
//! (templates, diagnostics, future features) can reference them without
//! needing a rebuild.

#[allow(dead_code)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/build_info.rs"));
}
pub use generated::*;
