//! Preamble comment block for generated files.
//!
//! Builds the copyright, license, and provenance comment that appears at the
//! top of every generated `.h` and `.c` file.

use crate::build_info;
use crate::resolve::FeatureSet;

/// Build the preamble comment block for a generated file.
///
/// The block includes:
///   - gloam version and the command line that produced the file
///   - MIT license notice for gloam itself
///   - Khronos Group copyright (always — all output derives from their XML)
///   - ANGLE copyright (only when GL/GLES/EGL supplementals contributed)
pub fn build_preamble(fs: &FeatureSet, command_line: &str) -> String {
    let mut lines: Vec<String> = Vec::new();
    let year = build_info::BUILD_YEAR;

    lines.push(format!(
        " * Generated by gloam {}. DO NOT EDIT.",
        build_info::VERSION
    ));
    lines.push(" *".to_string());
    lines.push(format!(" *   {command_line}"));

    // ---- gloam license ----
    lines.push(" *".to_string());
    lines.push(format!(" * gloam Copyright (c) {year} Steven Noonan"));
    lines.push(" * SPDX-License-Identifier: MIT".to_string());

    // ---- Khronos ----
    lines.push(" *".to_string());
    lines.push(
        " * Portions derived from Khronos Group XML API Registry specifications.".to_string(),
    );
    lines.push(format!(
        " * Copyright (c) 2013-{year} The Khronos Group Inc."
    ));
    lines.push(" * SPDX-License-Identifier: Apache-2.0".to_string());

    // ---- ANGLE (only for specs that use ANGLE supplementals) ----
    if uses_angle_supplementals(fs) {
        lines.push(" *".to_string());
        lines.push(
            " * Includes extensions from the ANGLE project (gl_angle_ext.xml, egl_angle_ext.xml)."
                .to_string(),
        );
        lines.push(format!(" * Copyright (c) {year} Google Inc."));
        lines.push(" * SPDX-License-Identifier: BSD-3-Clause".to_string());
    }

    format!("/*\n{}\n */", lines.join("\n"))
}

/// Returns true if this feature set includes ANGLE extension supplementals.
/// ANGLE extensions are loaded for GL-family and EGL specs.
fn uses_angle_supplementals(fs: &FeatureSet) -> bool {
    matches!(fs.spec_name.as_str(), "gl" | "egl")
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Minimal FeatureSet for testing — only spec_name matters here.
    fn stub_fs(spec_name: &str) -> FeatureSet {
        FeatureSet {
            spec_name: spec_name.to_string(),
            display_name: String::new(),
            apis: vec![],
            is_merged: false,
            is_vulkan: false,
            is_gl_family: false,
            context_name: String::new(),
            features: vec![],
            extensions: vec![],
            commands: vec![],
            types: vec![],
            flat_enums: vec![],
            enum_groups: vec![],
            feature_pfn_ranges: vec![],
            ext_pfn_ranges: Default::default(),
            ext_subset_indices: Default::default(),
            alias_pairs: vec![],
            required_headers: vec![],
        }
    }

    #[test]
    fn preamble_contains_version_and_command() {
        let fs = stub_fs("vk");
        let p = build_preamble(&fs, "gloam --api vk=1.3 c");
        assert!(p.contains(build_info::VERSION));
        assert!(p.contains("gloam --api vk=1.3 c"));
    }

    #[test]
    fn preamble_contains_gloam_mit_license() {
        let fs = stub_fs("vk");
        let p = build_preamble(&fs, "gloam --api vk=1.3 c");
        assert!(p.contains("Steven Noonan"));
        assert!(p.contains("SPDX-License-Identifier: MIT"));
    }

    #[test]
    fn preamble_contains_khronos_copyright() {
        let fs = stub_fs("vk");
        let p = build_preamble(&fs, "gloam --api vk=1.3 c");
        assert!(p.contains("Khronos Group"));
        assert!(p.contains("Apache-2.0"));
    }

    #[test]
    fn preamble_includes_angle_for_gl() {
        let fs = stub_fs("gl");
        let p = build_preamble(&fs, "gloam --api gl:core=3.3 c");
        assert!(p.contains("ANGLE"));
        assert!(p.contains("BSD-3-Clause"));
    }

    #[test]
    fn preamble_includes_angle_for_egl() {
        let fs = stub_fs("egl");
        let p = build_preamble(&fs, "gloam --api egl c");
        assert!(p.contains("ANGLE"));
    }

    #[test]
    fn preamble_excludes_angle_for_vulkan() {
        let fs = stub_fs("vk");
        let p = build_preamble(&fs, "gloam --api vk=1.3 c");
        assert!(!p.contains("ANGLE"));
        assert!(!p.contains("BSD-3-Clause"));
    }

    #[test]
    fn preamble_excludes_angle_for_glx() {
        let fs = stub_fs("glx");
        let p = build_preamble(&fs, "gloam --api glx c");
        assert!(!p.contains("ANGLE"));
    }

    #[test]
    fn preamble_is_valid_c_comment() {
        let fs = stub_fs("gl");
        let p = build_preamble(&fs, "gloam --api gl:core=3.3 c");
        assert!(p.starts_with("/*"));
        assert!(p.ends_with(" */"));
    }

    #[test]
    fn preamble_uses_build_year_not_hardcoded() {
        let fs = stub_fs("vk");
        let p = build_preamble(&fs, "gloam --api vk=1.3 c");
        let year = build_info::BUILD_YEAR.to_string();
        // gloam copyright should contain the build year.
        assert!(
            p.contains(&format!("Copyright (c) {year} Steven Noonan")),
            "gloam copyright should use BUILD_YEAR ({year})"
        );
        // Khronos copyright should contain the build year as the end of the range.
        assert!(
            p.contains(&format!("2013-{year} The Khronos Group")),
            "Khronos copyright range should end with BUILD_YEAR ({year})"
        );
    }
}
