//! `gloam regen` — regenerate existing output trees in place.
//!
//! Every generated tree records the exact command line that produced it in
//! `<tree>/.gloam/manifest.json`, so a tree is self-describing: regeneration
//! replays that command with the current gloam.  The recorded `--out-path`
//! is a historical record of the original invocation — it was relative to
//! whatever directory the user happened to generate from, which is
//! unknowable later — so replay derives the effective output path from the
//! manifest's own location instead, and re-records the original command line
//! verbatim.  Trees therefore regenerate correctly from any working
//! directory, and regeneration never rewrites the recorded command.
//!
//! By default each replay is pinned to the tree's recorded provenance
//! (`--lock` semantics): with an unchanged gloam the output is
//! byte-identical, and after a gloam change `git diff` shows exactly what
//! the change did.  `--fresh` re-resolves sources instead (bundled, or
//! upstream if the recorded command used `--fetch`), advancing the tree —
//! the normal update workflow.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use clap::Parser;

use crate::cli::{Cli, Generator};
use crate::diag::Diag;
use crate::provenance::manifest::{Manifest, SCHEMA_VERSION};

pub fn run(cli: Cli) -> Result<()> {
    let Generator::Regen(ref args) = cli.generator else {
        unreachable!("regen::run dispatched for a non-regen command");
    };
    let diag = Diag::new(cli.quiet);

    // (manifest path, explicitly named).  Problems in an explicitly named
    // manifest are hard errors; discovered candidates that turn out not to
    // be gloam manifests are skipped silently, because any project may
    // contain unrelated files named manifest.json.
    let mut manifests: Vec<(PathBuf, bool)> = Vec::new();
    for path in &args.paths {
        if path.is_file() {
            manifests.push((path.clone(), true));
        } else if path.is_dir() {
            let mut found = Vec::new();
            find_manifests(path, &mut found);
            found.sort();
            manifests.extend(found.into_iter().map(|p| (p, false)));
        } else {
            bail!("regen path {} is not a file or directory", path.display());
        }
    }

    let mut ran = 0usize;
    for (path, explicit) in &manifests {
        if replay(path, *explicit, args.fresh, cli.quiet, diag)? {
            ran += 1;
        }
    }
    if ran == 0 {
        bail!("no gloam manifests found under the given path(s)");
    }
    diag.info(format!("regenerated {ran} tree(s)"));
    // The suggested filter hides pure gloam-stamp churn: the C and Rust
    // preamble stamp lines, the manifest's gloam meta block (4-space
    // indent), and the output BOM's file hashes (6-space "blob"), which
    // track stamp changes byte-for-byte.  Ignoring 6-space "blob" lines is
    // safe even though provenance pins share the indent: a pin's blob never
    // changes without its sibling "commit" line (6-space, not filtered)
    // changing too, so a real source change always stays visible.
    diag.info(
        "review with: git diff -I'^ \\* @generated by gloam ' \
         -I'^// @generated by gloam ' -I'^    \"(version|describe|commit)\": ' \
         -I'^      \"blob\": '",
    );
    Ok(())
}

/// Recursively collect `manifest.json` files under `dir`.  `.git` is never
/// descended into; neither is `target`, because Cargo build directories can
/// hold packaged copies of real trees (`target/package/...`) that must not
/// be regenerated in place.  A tree that genuinely lives under a directory
/// named `target` can still be regenerated by naming it explicitly.
fn find_manifests(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            if path
                .file_name()
                .is_some_and(|n| n == ".git" || n == "target")
            {
                continue;
            }
            find_manifests(&path, out);
        } else if path.file_name().is_some_and(|n| n == "manifest.json") {
            out.push(path);
        }
    }
}

/// Replay the command recorded in one manifest.  Returns `Ok(true)` if a
/// tree was regenerated and `Ok(false)` if the candidate was skipped (only
/// possible for discovered, non-explicit candidates).
fn replay(
    manifest_path: &Path,
    explicit: bool,
    fresh: bool,
    quiet: bool,
    diag: Diag,
) -> Result<bool> {
    let text = match std::fs::read_to_string(manifest_path) {
        Ok(text) => text,
        Err(e) if explicit => {
            return Err(e).with_context(|| format!("reading {}", manifest_path.display()));
        }
        Err(_) => return Ok(false),
    };
    let manifest = match Manifest::from_json(&text) {
        Ok(m) => m,
        Err(e) if explicit => {
            return Err(e)
                .with_context(|| format!("{} is not a gloam manifest", manifest_path.display()));
        }
        Err(_) => return Ok(false),
    };
    if manifest.schema_version != SCHEMA_VERSION {
        if explicit {
            bail!(
                "{} has schema_version {}, but this gloam understands {}",
                manifest_path.display(),
                manifest.schema_version,
                SCHEMA_VERSION
            );
        }
        diag.warn(format!(
            "{}: skipping (schema_version {} != {})",
            manifest_path.display(),
            manifest.schema_version,
            SCHEMA_VERSION
        ));
        return Ok(false);
    }

    let recorded = manifest.gloam.command_line;
    let tokens: Vec<&str> = recorded.split_whitespace().collect();
    if tokens.first().copied() != Some("gloam") {
        if explicit {
            bail!(
                "{} does not record a gloam command line (got '{recorded}')",
                manifest_path.display()
            );
        }
        return Ok(false);
    }
    let mut replay_cli = Cli::try_parse_from(&tokens).with_context(|| {
        format!(
            "re-parsing the command recorded in {}: '{recorded}'",
            manifest_path.display()
        )
    })?;

    // Verbosity follows the regen invocation, not the recorded command.
    replay_cli.quiet = quiet;
    if !fresh {
        replay_cli.lock = Some(manifest_path.to_path_buf());
    }

    let target = match &mut replay_cli.generator {
        Generator::C(_) | Generator::Rust(_) => {
            // A generation manifest lives at <tree>/.gloam/manifest.json, so
            // its own location is the authoritative output path.  The
            // recorded --out-path (relative to the original invocation's
            // cwd) is preserved in the re-recorded command line but ignored
            // for placement.
            let tree = manifest_path
                .parent()
                .filter(|p| p.file_name().is_some_and(|n| n == ".gloam"))
                .and_then(Path::parent);
            let Some(tree) = tree else {
                if explicit {
                    bail!(
                        "{} records a generation command but does not live at \
                         <tree>/.gloam/manifest.json",
                        manifest_path.display()
                    );
                }
                return Ok(false);
            };
            // parent() of a bare relative ".gloam/manifest.json" is "" —
            // that tree root is the current directory.
            let tree = if tree.as_os_str().is_empty() {
                Path::new(".")
            } else {
                tree
            };
            replay_cli.out_path = tree.display().to_string();
            replay_cli.out_path.clone()
        }
        Generator::Lock(lock_args) => {
            // A lock snapshot is the manifest file itself; rewrite in place.
            lock_args.out = manifest_path.display().to_string();
            lock_args.out.clone()
        }
        Generator::Regen(_) => {
            bail!(
                "{} records a regen command — refusing to recurse",
                manifest_path.display()
            );
        }
    };

    diag.info(format!("· {target} $ {recorded}"));
    crate::execute(replay_cli, &recorded).with_context(|| format!("regenerating {target}"))?;
    Ok(true)
}
